package erik.study.mybatis.common.mapper.generator.domain;

import javax.persistence.*;

@Table(name = "`country`")
public class Country {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column country.id
     *
     * @mbg.generated Wed Feb 26 15:20:28 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column country.country_name
     *
     * @mbg.generated Wed Feb 26 15:20:28 CST 2020
     */
    private String countryName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column country.country_code
     *
     * @mbg.generated Wed Feb 26 15:20:28 CST 2020
     */
    private String countryCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column country.id
     *
     * @return the value of country.id
     *
     * @mbg.generated Wed Feb 26 15:20:28 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column country.id
     *
     * @param id the value for country.id
     *
     * @mbg.generated Wed Feb 26 15:20:28 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column country.country_name
     *
     * @return the value of country.country_name
     *
     * @mbg.generated Wed Feb 26 15:20:28 CST 2020
     */
    public String getCountryName() {
        return countryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column country.country_name
     *
     * @param countryName the value for country.country_name
     *
     * @mbg.generated Wed Feb 26 15:20:28 CST 2020
     */
    public void setCountryName(String countryName) {
        this.countryName = countryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column country.country_code
     *
     * @return the value of country.country_code
     *
     * @mbg.generated Wed Feb 26 15:20:28 CST 2020
     */
    public String getCountryCode() {
        return countryCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column country.country_code
     *
     * @param countryCode the value for country.country_code
     *
     * @mbg.generated Wed Feb 26 15:20:28 CST 2020
     */
    public void setCountryCode(String countryCode) {
        this.countryCode = countryCode;
    }
}