package erik.study.mybatis.common.mapper.generator.mapper;

import erik.study.mybatis.common.mapper.generator.domain.Country;
import erik.study.mybatis.common.mapper.generator.domain.CountryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import tk.mybatis.mapper.common.Mapper;

public interface CountryMapper extends Mapper<Country> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table country
     *
     * @mbg.generated Wed Feb 26 15:20:28 CST 2020
     */
    long countByExample(CountryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table country
     *
     * @mbg.generated Wed Feb 26 15:20:28 CST 2020
     */
    int deleteByExample(CountryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table country
     *
     * @mbg.generated Wed Feb 26 15:20:28 CST 2020
     */
    List<Country> selectByExample(CountryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table country
     *
     * @mbg.generated Wed Feb 26 15:20:28 CST 2020
     */
    int updateByExampleSelective(@Param("record") Country record, @Param("example") CountryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table country
     *
     * @mbg.generated Wed Feb 26 15:20:28 CST 2020
     */
    int updateByExample(@Param("record") Country record, @Param("example") CountryExample example);
}